//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public string AdSoyad { get; set; }
        public string Sifre { get; set; }
        public System.DateTime SonGiris { get; set; }
        public bool Hiper { get; set; }
    }
}
