//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gelinlikler
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Detay { get; set; }
        public bool Anasayfa { get; set; }
        public int Beden { get; set; }
        public int Sezon { get; set; }
        public int KesimId { get; set; }
        public int RenkId { get; set; }
        public int SiluetId { get; set; }
        public int YakaTipiId { get; set; }
        public int KumasId { get; set; }
        public bool YeniSezon { get; set; }
        public bool OzelUrun { get; set; }
        public bool EnCokSatan { get; set; }
        public bool Yeni { get; set; }
        public int Oncelik { get; set; }
        public bool Goster { get; set; }
        public int DilKod { get; set; }
    }
}
