//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gelinlikfotograflari
    {
        public int Id { get; set; }
        public int GelinlikId { get; set; }
        public string FotoKucuk { get; set; }
        public string FotoBuyuk { get; set; }
        public bool Anasayfa { get; set; }
        public bool OnFoto { get; set; }
        public bool ArkaFoto { get; set; }
        public string Etiket { get; set; }
    }
}
