//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class teksayfalar
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Kod { get; set; }
        public string Fotograf { get; set; }
        public string Icerik { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int AdminId { get; set; }
        public int OkunmaSayisi { get; set; }
        public int Oncelik { get; set; }
        public bool Goster { get; set; }
        public int DilKod { get; set; }
    }
}
