//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWorld.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorumlar
    {
        public int Id { get; set; }
        public int UstYorumId { get; set; }
        public int GelinlikId { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Ip { get; set; }
        public bool Goster { get; set; }
    }
}
